// Generated by CoffeeScript 1.6.3
(function() {
  require({
    urlArgs: '',
    baseUrl: 'js',
    paths: {
      underscore: '../../build/js/lib/underscore/underscore-min',
      eventedarray: '../../build/js/EventedArray'
    },
    shim: {
      'underscore': {
        exports: '_'
      }
    }
  });

  require(['underscore', 'eventedarray', 'EventedArrayRequireSpec'], function(_, EventedArray, EventedArrayRequireSpec) {
    var htmlReporter, jasmineEnv;
    jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 1000;
    htmlReporter = new jasmine.HtmlReporter();
    jasmineEnv.addReporter(htmlReporter);
    jasmineEnv.specFilter = function(spec) {
      return htmlReporter.specFilter(spec);
    };
    return jasmineEnv.execute();
  });

}).call(this);
